### ISSUE TITLE
Do you finish assemble SOLO 12 now?

### ISSUE THREAD

**Issue by laniakeawhite** [Lhumd/robot_properties_bolt#2]
I found in [this link](https://odri.discourse.group/t/youre-building-an-odri-robot-tell-us-about-it/533/5?u=laniakeawhite) that you are assembling SOLO 12, and order  micro driver yourself。

Do you get your micro driver now? I  order micro driver from a PCB company,but have some problems, when controlling motor,nothing goes right.

I don't know whether the hardware of micro driver itself has problems,or the firmware is not suitable for mirco driver.
The firmware i used is udriver V2.
Are there some code of udriver need to be modified to fit the micro driver? or no need to change any code about udriver firmware?
I have posted my problems to odri.discourse.group,but no one tell me how to deal with the problem.

If you can tell me how to make micro driver work well, it will be very thankful. 

Thinks.

**Comment by Lhumd** [comment]
Hi,

We bought an unassembled robot from PAL Robotics. We didn't directly order any PCB. Unfortunately, I am not an expert in the area of your questions and I cannot help you with it.

I saw Felix answered your post [here](https://odri.discourse.group/t/problems-about-micro-driver/650/13l).

I can understand that you had a hard time finding the solution to your problem, but I suggest keeping the GitHub issues related to the repository's subject. You can send a direct message to users in odri.discourse.group if you need to.

I'm closing this thread as it had nothing to do with this package.
